schema = 3

[mod]
  [mod."github.com/lithammer/fuzzysearch"]
    version = "v1.1.8"
    hash = "sha256-aMMRcrlUc9CBiiNkcnWWn4hfNMNyVhrAt67kvP4D4Do="
  [mod."github.com/spf13/pflag"]
    version = "v1.0.10"
    hash = "sha256-uDPnWjHpSrzXr17KEYEA1yAbizfcsfo5AyztY2tS6ZU="
  [mod."github.com/yuin/goldmark"]
    version = "v1.7.13"
    hash = "sha256-vBCxZrPYPc8x/nvAAv3Au59dCCyfS80Vw3/a9EXK7TE="
  [mod."golang.org/x/text"]
    version = "v0.9.0"
    hash = "sha256-tkhDeMsSQZr3jo7vmKehWs3DvWetwXR0IB+DCLbQ4nk="
